# Generated by Django 3.2.21 on 2024-02-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_userpreference1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference1',
        ),
    ]
